name: Deploy PR Preview

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Deploy to temporary branch
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pr-preview-${{ github.event.pull_request.number }}
          FOLDER: site
          CLEAN: true

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: 'Preview site is available at: https://<username>.github.io/<repository>/pr-preview-${{ github.event.pull_request.number }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Delete preview branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: git push origin --delete pr-preview-${{ github.event.pull_request.number }}
