name: Send Release Notes to Slack

on:
  release:
    types: [published]
    
jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Slack message payload
        id: generate_payload
        run: |
          python slack_bot_generate_payload.py
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_BODY: ${{ github.event.release.body }}

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: ${{ steps.generate_payload.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
