name: Notify Slack of New Release

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Slack Notification
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        RELEASE_BODY="${{ github.event.release.body }}"
        RELEASE_BODY_ESCAPED=$(echo "$RELEASE_BODY" | sed 's/"/\\"/g; s/\n/\\n/g')
        
        PAYLOAD=$(cat <<- EOM
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":sparkles: *Version $VERSION of the Lighthouse API Standards has been released:*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$RELEASE_BODY_ESCAPED"
                }
              }
            ]
          }
        EOM
        )

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ secrets.SLACK_WEBHOOK_URL }}
